import Head from "next/head";
import Image from "next/image";
import { useAccount } from "wagmi";
import Link from "next/link";
import { Button } from "../components/elements";

import { Account, Connect, NetworkSwitcher } from "../components/wallet";

const navItems = [
  {
    label: "WhiteList",
    href: "/whitelist",
  },
  {
    label: "Mint",
    href: "/mint",
  },
];

export default function Home() {
  const [{ data: accountData }] = useAccount();
  return (
    <div className={"bg-gray-900 text-white h-screen"}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={""}>
        <h1 className="text-3xl font-bold text-center">Crypto Devs</h1>
        <div className={"border my-4 p-4"}>
          {navItems.map((nav, id) => (
            <Link key={id} href={nav.href} passHref>
              <Button>{nav.label}</Button>
            </Link>
          ))}
        </div>
        <div className={"border my-4 p-4"}>
          <div>account</div>

          <Account />
          <div>switcher</div>

          <NetworkSwitcher />
        </div>
        <div className={"border my-4 p-4"}>
          <div>connect</div>
          <Connect />
        </div>
      </main>

      <footer className={""}></footer>
    </div>
  );
}
